name: ragali
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>=3.10
  - xarray
  - netcdf4
  - matplotlib
  - shapely
  - pandas
  - sparse
  # maybe the things below should be optional later to keep the env lightweight
  - ipywidgets
  - cartopy
